### ISSUE TITLE
No good way of getting a list of stops/stations for a route, regardless of the date now.

### ISSUE THREAD

**Issue by christianbernier** [mbta/api#261]
My site works by using the API to fetch which stations/stops are on a route to show to the user (I chose to do this since they change somewhat frequently on bus routes). It used to work perfectly with using /shapes?filter[route]=, but now that the /shapes endpoint changed to just the polylines, there's no good way of getting a list of stations/stops for a particular route. I've tried using representative trips from route_patterns, but sometimes those are empty, depending on if the route is running that day.

Would it be possible to bring back some easy way of getting stops based on routes, not just lines?

Thanks!

**Comment by digitalcora** [comment]
You can get stops on a route using a `route` filter on the `stops` endpoint. For example, `/stops?filter[route]=7` retrieves the stops on bus route 7. Is this what you were looking for?

**Comment by christianbernier** [comment]
Thanks for the reply. That's not exactly what I'm looking for. I need to be able to differentiate between different branches, for instance. So on the red line, `/stops?filter[route]=Red` gives all the stops on the red line, from both the Ashmont and Braintree branches. What I'm looking for is a way to get just the stops on the Ashmont branch, then just the stops on the Braintree branch, like I could before using shapes.

Please let me know if there's a better way to do what I'm trying to do.

Thanks!

**Comment by christianbernier** [comment]
It would be very helpful to include the

**Comment by digitalcora** [comment]
@christianbernier In this case a "branch" is roughly analogous to what we call a `RoutePattern`, which is a grouping of trips that all have the same route, shape, and stops. `RoutePattern` has a singular `representative_trip` relationship that returns one of these trips, arbitrarily, and you then have a list of stops via the `stops` relationship.

For example, having determined from `/route_patterns?filter[route]=Red` that the typical "Alewife - Ashmont" pattern is `Red-1-0`, we can make this request:

```
/route_patterns/Red-1-0?include=representative_trip.stops
```

The `included` contains the data for all stops on the pattern's representative trip (`include=representative_trip` would also work if all you wanted was the stop IDs, as they are expressed in the trip's `stops` relationship itself). And of course, these could be combined into a single request to `/route_patterns` to get all the patterns and all of their stops in one shot.

Note that in most cases you'd want to determine `RoutePattern` IDs programmatically or allow users of your site to select one, rather than hard-coding them. Especially with bus service, there is often no single "list of stops for a route", as routes can have multiple stopping patterns that differ substantially from each other. Even patterns that only differ in their `direction` may have different stops. The ideal approach would depend on the purpose of your site.

**Comment by christianbernier** [comment]
Thanks for the quick response. I think that's exactly what I want, so thank you! I currently have it built in so users can determine route patterns, which is determined programmatically, as you mentioned.

Thank you!

**Comment by digitalcora** [comment]
Glad I could help 😃

Also, I'm not sure if this was the case based on your initial description, but if you had a live site break due to API changes, keep in mind you can always lock your requests to a specific API version [as documented here](https://www.mbta.com/developers/v3-api/versioning). Because removing the `shape.stops` relationship was a backwards-incompatible change, we created a new API version for it, and it remains available in all [previous versions](https://www.mbta.com/developers/v3-api/changelog). This would allow your site to keep working as-is while you update it.

**Comment by christianbernier** [comment]
Oh I didn't even realize that—thanks! I'll definitely make sure to do that in the future haha
