### ISSUE TITLE
Fitchburg Line not returning any data

### ISSUE THREAD

**Issue by thatkraftkid** [mbta/api#383]
In the last week or so, I've noticed an issue with api calls involving the Fitchburg Line. (This originated within Home Assistant, but while troubleshooting I've confirmed the issue happens outside of the HA environment as well.) 

I've just been trying to track when the Fitchburg Line will be arriving at my stop, and if there are any delays. However, using the route as the basis for a call doesn't return any information.

For example, if I try the Fairmount line 

`https://api-v3.mbta.com/predictions?include=schedule%2Cstop%2Calerts&filter%5Broute%5D=CR-Fairmount` 

I get plenty back. 

The same goes for Newburyport.

`https://api-v3.mbta.com/predictions?include=schedule%2Cstop%2Calerts&filter%5Broute%5D=CR-Newburyport`

If I try to make the same call with Fitchburg 

`https://api-v3.mbta.com/predictions?include=schedule%2Cstop%2Calerts&filter%5Broute%5D=CR-Fitchburg` 

all I get is 

`{"data":[],"jsonapi":{"version":"1.0"}}`

If I call this:

`https://api-v3.mbta.com/routes/CR-Fitchburg`

it shows that the naming convention for routes is consistent, but I can't get any data if I use "CR-Fitchburg". So it seems like for whatever reason something's up with the Fitchburg end of things.

Even just trying to get the schedule comes up empty.

`https://api-v3.mbta.com/schedules?filter%5Bdirection_id%5D=1&filter%5Broute_type%5D=2&filter%5Broute%5D=CR-Fitchburg`

**Comment by thatkraftkid** [comment]
This has changed slightly, but it looks like it's returning data for the Haverhill/Lawrence Line, rather than Fitchburg.

If I make this call:
`https://api-v3.mbta.com/schedules?filter%5Bdirection_id%5D=1&filter%5Broute_type%5D=2&filter%5Broute%5D=CR-Fitchburg`

This is the result (or part of it, anyway):
<pre>
{
  "data": [{
        "attributes": {
          "arrival_time": null,
          "departure_time": null,
          "direction_id": 1,
          "schedule_relationship": null,
          "status": "On time",
          "stop_sequence": 160
        },
        "id": "prediction-CR-479338-422-HaverhillLawrence-BNT-0000-160",
        "relationships": {
          "alerts": {
            "data": [{
              "id": "382824",
              "type": "alert"
            }, {
              "id": "381048",
              "type": "alert"
            }]
          },
          "route": {
            "data": {
              "id": "CR-Fitchburg",
              "type": "route"
            }
          },
          "schedule": {
            "data": {
              "id": "schedule-CR-479338-422-HaverhillLawrence-BNT-0000-160",
              "type": "schedule"
            }
          },
          "stop": {
            "data": {
              "id": "BNT-0000",
              "type": "stop"
            }
          },
          "trip": {
            "data": {
              "id": "CR-479338-422-HaverhillLawrence",
              "type": "trip"
            }
          },
          "vehicle": {
            "data": null
          }
        },
        "type": "prediction"
      }, {
        "attributes": {
          "arrival_time": null,
          "departure_time": null,
          "direction_id": 0,
          "schedule_relationship": null,
          "status": "Departed",
          "stop_sequence": 0
        },
        "id": "prediction-CR-479339-417-HaverhillLawrence-BNT-0000-06-0",
        "relationships": {
          "alerts": {
            "data": [{
              "id": "382824",
              "type": "alert"
            }, {
              "id": "381048",
              "type": "alert"
            }]
          },
          "route": {
            "data": {
              "id": "CR-Fitchburg",
              "type": "route"
            }
          },
          "schedule": {
            "data": {
              "id": "schedule-CR-479339-417-HaverhillLawrence-BNT-0000-0",
              "type": "schedule"
            }
          },
          "stop": {
            "data": {
              "id": "BNT-0000-06",
              "type": "stop"
            }
          },
          "trip": {
            "data": {
              "id": "CR-479339-417-HaverhillLawrence",
              "type": "trip"
            }
          },
          "vehicle": {
            "data": null
          }
        },
        "type": "prediction"
      },
</pre>

**Comment by digitalcora** [comment]
Hi, could you elaborate on what exactly isn't working for you, or what you're expecting to see? We use these same API endpoints and calls extensively on the MBTA web site, for example on the [Fitchburg line page](https://www.mbta.com/schedules/CR-Fitchburg/line), and currently everything appears to be working. It also doesn't look like there's anything unusual about the predictions response you pasted. If you look at the `route` relationship, you can see that they are predictions for the `CR-Fitchburg` route, as requested.

If you're confused about why the `id` of the predictions includes the string `HaverhillLawrence`, this is because trip IDs sometimes include strings related to active disruptions or service adjustments, even on unrelated routes (due to internal details of how our GTFS feed is generated). Keep in mind all `id` values are intended to be opaque — you should not count on them having any particular format or meaning.

**Comment by thatkraftkid** [comment]
The initial issue was that any call to the Fitchburg line would only return `{"data":[],"jsonapi":{"version":"1.0"}}` without any data. At some point that stopped happening.

Within HomeAssistant I have a card that displays when the next train will be arriving at the Fitchburg Line stops I use, and if there are delays in either direction. When I posted the issue I was getting errors because no data was found. Cross-checking with the schedule page, they seem to be accurate. The Haverhill/Lawrence id seems to be a red herring, since it ultimately isn't part of the data I use. It just looked suspect given that calls to the Fitchburg line hadn't been working at all, then when they did, there seemed to be extraneous data in there. (Thank you for explaining why that is.)

I'll close this out since it appears to be working now.

**Comment by digitalcora** [comment]
@thatkraftkid Good to know it's working for you! FYI, since there are some known issues with the current Commuter Rail tracking hardware, it is not unusual for a train to be running with no corresponding predictions in the API. If real-time tracking is offline for _all_ running trains on a route (which could be as few as 1 train, at some hours), you would see `"data":[]`.

As we mentioned in a [topic on the developers mailing list](https://groups.google.com/g/massdotdevelopers/c/xy7EVRvNvN4):

> a program is underway to replace the AVL tracking system for the Commuter Rail fleet. [...] That new vehicle-tracking equipment is currently in its testing phase, with a full rollout expected this calendar year, however at this time a more precise timetable is not available.
